{{--
    Dynamic form fields generated by FormBuilder service.

    FormBuilder automatically generates form HTML from Field attributes on content models.
    This replaces the previous hard-coded Blade template with dynamic generation.
--}}

{!! $formBuilder->buildForm($modelClass, $content ?? null) !!}
